# Auto-generated by tools/sandbox_sim.py — reinstalls the
# tournament sandbox in child processes.
import os, sys
if os.environ.get('SANDBOX_SIM_ACTIVE') == '1':
    sys.path.insert(0, '/mnt/c/Users/rahil/downloads/3600-bot/tools')
    try:
        import sandbox_sim
        sandbox_sim.install_sandbox()
    except Exception as e:
        sys.stderr.write(f'[sandbox_sim] child-reinstall failed: {e}\n')
